name: 'netsuite_project'
version: '1.0.0'
config-version: 2

profile: 'netsuite_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  
on-run-end: # execute the dbt log package if target is 'prod'
  - "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"

vars:

  # Technical parameters :
  dbt_start_datetime              : '{{ run_started_at.astimezone(modules.pytz.timezone("Europe/Paris")).strftime("%Y-%m-%d %H:%M:%S") }}'
  dbt_start_date                  : '{{ run_started_at.astimezone(modules.pytz.timezone("Europe/Paris")).strftime("%Y-%m-%d") }}'
  dbt_run_id                      : '{{ invocation_id }}'
  future_proof_date               : '9999-12-31'
  past_proof_date                 : '1900-01-01'
  scd_excluded_col_name           : ['dbt_scd_id', 'dbt_updated_at', 'dbt_valid_from', 'dbt_valid_to', 'scd_valid_from_fill_date', 'scd_valid_to_fill_date', 'version_number']
  date_table_start_date           : '2020-01-01'
  date_table_window_year          : '5'
  date_table_fiscal_month         : '2'

  # Custom column names :   
  dbt_snapshot_col_name           : 'dbt_functional_snapshot_date'
  dbt_load_datetime_col_name      : 'dbt_load_datetime'
  dbt_run_id_col_name             : 'dbt_run_id'

  # Constraint names :    
  pk_transaction_with_line        : 'pk_transaction_with_line'

  # Dimensions keys column names :
  item_key                        : 'item_nsid'
  business_unit_key               : 'bu_nsid'
  customer_key                    : 'customer_nsid'
  item_category_key               : 'item_category_nsid'
  item_pattern_key                : 'item_pattern_nsid'

  # Fact key column names :
  all_transactions_with_line_key  : 'all_transactions_with_line'

  # Dynamic currency definition :
  fx_avg_implicit_currency        : 'EUR'

  # Scope of snapshotted data :
  transaction_snapshot_type       : ['Opportunity', 'Invoice', 'Sales Order']

  # Scope of the virtualized DWH :
  all_transactions_scope_type     : ['Opportunity', 'Invoice', 'Sales Order', 'Journal Entry']
  all_transactions_scope_date     : '2023'

  # Scope of the sales dataset
  sales_scope_type                : ['Opportunity', 'Invoice', 'Sales Order']
  opportunity_open_scope          : ['Under Discussion', 'Ongoing']
  sales_order_open_scope          : ['Under Discussion', 'Ongoing']

  # DQ & exhaustivity control in Dbt for opportunity status :
  opportunity_closed_scope        : ['Closed - Won', 'Closed - Lost']
  sales_order_closed_scope        : ['Closed - Won', 'Closed - Lost']

models:
  dbt_artifacts:
    +schema: log
  netsuite_project:
    prp:
      +schema: prp
    scd:
      +schema: scd
    dwh:
      +schema: dwh
      transaction_with_line:
        +pre-hook: '{{ hook_transaction_drop_pk_constraint() }}'
        +post-hook: ['{{ hook_transaction_add_not_null() }}','{{ hook_transaction_add_pk() }}']
    bus:
      +schema: bus
    ds:
      +schema: ds
      +materialized: table

seeds:
  netsuite_project:
    stg:
      +schema: stg
      +delimiter: ";"