netsuite_project:
  target: docker
  outputs:
    dev:
      type: sqlserver
      host: localhost 
      port: 1433
      database: netsuite
      driver: 'ODBC Driver 17 for SQL Server'
      schema: "{{ var('branch_name') }}"
      encrypt: false
      trust_cert: true
      windows_login: true
    prod:
      type: sqlserver
      host: localhost
      port: 1433
      database: netsuite
      driver: 'ODBC Driver 17 for SQL Server'
      schema: prod
      encrypt: false
      trust_cert: true
      windows_login: true
    docker_dev:
      type: sqlserver
      host: localhost
      port: 1433
      database: netsuite
      driver: 'ODBC Driver 17 for SQL Server'
      schema: "{{ var('branch_name') }}"
      encrypt: false
      trust_cert: true
      windows_login: false  
      user: sa
      password: Strong&Password=94210
    docker_prod:
      type: sqlserver
      host: localhost
      port: 1433
      database: netsuite
      driver: 'ODBC Driver 17 for SQL Server'
      schema: prod
      encrypt: false
      trust_cert: true
      windows_login: false  
      user: sa
      password: Strong&Password=94210