netsuite_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      host: localhost 
      port: 1433
      database: netsuite
      driver: 'ODBC Driver 17 for SQL Server'
      schema: dbo
      encrypt: false
      trust_cert: true
      windows_login: true
      