apiVersion: batch/v1
kind: CronJob
metadata:
  name: netsuite-dbt-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dbt
            image: gabriellegall/dbt-netsuite-image
            command: ["make", "dbt_prod_soft_reset"]
          restartPolicy: Never