# Assuming that the [host], [user] and [password] are hard coded in the profiles.yml, the following command would work:

apiVersion: v1
kind: Pod
metadata:
  name: netsuite-dbt-container
spec:
  containers:
  - name: dbt
    image: gabriellegall/dbt-netsuite-image
    tty: true
    stdin: true 
    command: ["make", "dbt_prod_hard_reset"]
  restartPolicy: Never