# To do : check the Pk on snapshotted data to ensure that the column snapshot date is indeed considered, and not just a string

version: 2

models:
  - name: transaction_with_line
    description: 
      This table contains all the latest transactions from NetSuite.
      The data load is incremental, based on the latest modification dates since the last datawarehouse insert.
      Hard deleted transaction records in NetSuite are stored under the deleted_records table and are deleted from the datawarehouse as well.
      Hard deleted transactionline records are managed through the delete+insert loading option, set-up at the transaction level.
    columns:
      - name: transaction_status
        tests:
          - accepted_values:
              name: unexpected_opportunity_status
              values: '{{ var("opportunity_open_scope") + var("opportunity_closed_scope") }}'
              config:
                where: "transaction_type = 'Opportunity'"
                severity: warn
      - name: transaction_status
        tests:
          - accepted_values:
              name: unexpected_sales_order_status
              values: '{{ var("sales_order_open_scope") + var("sales_order_closed_scope") }}'
              config:
                where: "transaction_type = 'Sales Order'"
                severity: warn
            
  - name: historized_transaction_with_line
    description: 
      This table contains a snapshot of the transactions from NetSuite. 
      For performance and storage efficiency reasons, the snapshot of a subset of all the data is taken once a month.
      The snapshot is taken automatically if no data was snapshotted in the previous month.
    columns:
      - name: '{{ var("dbt_snapshot_col_name") }}'
        description: end-of-month snapshot date from a business perspective
      - name: '{{ var("dbt_load_datetime_col_name") }}'
        description: actual snapshot date from a technical perspective
      - name: transaction_nsid
        tests:
          - not_null
      - name: transaction_line_nsid
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - var("dbt_snapshot_col_name")
            - transaction_nsid
            - transaction_line_nsid