version: 2

models:
  - name: transaction_with_line
    columns:
      - name: transaction_status
        tests:
          - accepted_values:
              name: unexpected_opportunity_status
              values: '{{ var("opportunity_open_scope") + var("opportunity_closed_scope") }}'
              config:
                where: "transaction_type = 'Opportunity'"
                severity: warn
      - name: transaction_status
        tests:
          - accepted_values:
              name: unexpected_sales_order_status
              values: '{{ var("sales_order_open_scope") + var("sales_order_closed_scope") }}'
              config:
                where: "transaction_type = 'Sales Order'"
                severity: warn