version: 2

models:
  - name: prep_delta_records
    description: 
      This table contains the list of all transaction_nsid and the latest modification date, either at the transaction_nsid level, or at the transaction_line_nsid level.
      This information is used to update the DWH transactions with line table using an incremental mode, based on the transaction_nsid key.
  - name: prep_budget_for_union
    description: 
      This table contains the budget data, enriched with all the relevant columns that are expected to match the dataset with which it will be merged.
  - name: prep_dim_bu_alternate_key_bu_code
    description: 
      This table is a workaround solution requested by the client to be able to enrich the budget data with the business unit dimension table.
      The budget data does not contain any usual join key in the form of a NetSuite ID (nsid) because it is an external file input.
      The best proxy indicated by the client is to use the business unit code instead.
      Since the business unit code is not expected to be unique all the time, a data transformation is required to match the latest primary key.
  - name: prep_fx_avg_rate_unpivot
    description: 
      This table normalizes the months of the FX rates file and adds a USD-USD exchange rate of 1.
      This information is used to convert amounts in a consistent manner accross the client's finance and treasury team.
  - name: prep_rls_normalize
    description: 
      This table normalizes the RLS information, when multivalued attributes are separated by a comma.
      This information is used to manage dataset dynamic row-level-security at a user level.
      The column row_id identifies the set of conditons for the user. The intersection of all conditions within a row_id defines the security rule. 
      Conditions are additive if several row_id are recorded for a single user. This is a simple way to manage advanced conditions.
  - name: prep_transaction_with_lines_for_union
    description: 
      This table defines the current date from Dbt as a functional snapshot date for the current transaction data.
      This information is used to differentiate the snapshotted data and the current data when merged together.