# To do : check the Pk on snapshotted data to ensure that the column snapshot date is indeed considered, and not just a string

version: 2

models:
  - name: fact_all_transactions_with_line
    description: 
      This table consolidates all the transactions and transaction lines - both current and historized (snapshotted). 
      A snapshot date field can be use to differentiate the different versions of the transactions data.
      This table also centralizes the first joins with the dimensions that are common to all transaction types (e.g. Business Unit).
    columns:
      - name: fx_rate_original_to_usd
        tests:
          - not_null:
              config:
                severity: error
      - name: fx_rate_original_to_dynamic
        tests:
          - not_null:
              config:
                severity: error
  - name: dim_bu
    description: 
      This dimension table returns, for any business unit primary key, both (1) the historical attribute, and (2) the current attribute.
  - name: dim_customer
    description: 
      This dimension table returns, for any customer primary key, both (1) the historical attribute, and (2) the current attribute.
  - name: dim_item
    description: 
      This dimension table returns, for any item primary key, both (1) the historical attribute, and (2) the current attribute.
  - name: dim_date
    description: 
      This dimension date table contains all date attributes for time-intelligent calculations and advanced filtering (e.g. YTD).
  - name: fact_fx_avg_rate_dated
    description: 
      This average fx rate table contains the normalized fx rates for every month. 
      This table also calculates the implicit dynamic exchange rate - based on the USD rate.
  - name: fact_fx_avg_rate_latest
    description: 
      This average fx rate table contains the normalized fx rates for the latest month available only.
      This is the rate to be used when the dated fx rate (previously defined) is not available.
      This table also calculates the implicit dynamic exchange rate - based on the USD rate.
