name: dbt_prod_full_reset

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  dbt_prod_full_reset_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_repository
        uses: actions/checkout@v3

      - name: dbt_prod_run
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/netsuite_project \
            -w /netsuite_project \
            gabriellegall/dbt-netsuite-image \
            bash -c "dbt deps && make dbt_prod_hard_reset"
