name: dbt_prod_doc_serve

on:
  push:
    branches:
      - master

jobs:
  # Job to generate and upload artifacts (docs)
  dbt_prod_doc_serve_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v3
        
      - name: dbt_compile_and_generate_docs
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/netsuite_project \
            -w /netsuite_project \
            gabriellegall/dbt-netsuite-image \
            bash -c "
              export SQLSERVER_HOST='${{ secrets.SQLSERVER_HOST }}' &&
              export SQLSERVER_USER='${{ secrets.SQLSERVER_USER }}' &&
              export SQLSERVER_PASSWORD='${{ secrets.SQLSERVER_PASSWORD }}' &&
              dbt deps &&
              make dbt_prod_compile &&
              make dbt_prod_doc_generate
            "
            
      - name: upload_dbt_doc
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: target/
          retention-days: 7

  deploy_to_github_pages_job:
    needs: dbt_prod_doc_serve_job
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy_to_github_pages
        id: deployment
        uses: actions/deploy-pages@v4
