name: dbt_dev_drop_schema

on:
  pull_request:
    branches:
      - master  # Triggers when a pull request is merged into main
    types: [closed]  # Only triggers when the pull request is closed (merged)

jobs:
  dbt_dev_drop_schema_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # Check out the source branch of the pull request

      - name: drop_development_schema
        run: |
          "
          docker run --rm \
            -v ${{ github.workspace }}:/netsuite_project \
            -w /netsuite_project \
            gabriellegall/dbt-netsuite-image \
            bash -c "
              export SQLSERVER_HOST='${{ secrets.SQLSERVER_HOST }}' &&
              export SQLSERVER_USER='${{ secrets.SQLSERVER_USER }}' &&
              export SQLSERVER_PASSWORD='${{ secrets.SQLSERVER_PASSWORD }}' &&
              dbt deps &&
              make dbt_prod_run
            "
