name: test_development_schema_upon_pr

on:
  pull_request:
    branches:
      - master # Triggers on pull requests to the master branch
    types: [opened, synchronize]  # Runs when a PR is opened or synchronized (updated)

jobs:
  run-dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout_repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Check out the source branch of the pull request

      - name: dbt_test_branch
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/netsuite_project \
            -w /netsuite_project \
            gabriellegall/dbt-netsuite-image \
            bash -c "dbt deps && make dbt_test"
