name: dbt_artifacts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at minute 0
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  dbt-regular-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: dbt_prod_run
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/netsuite_project \
            -w /netsuite_project \
            gabriellegall/dbt-netsuite-image \
            bash -c "dbt deps && dbt compile"

      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prod_run_artifacts
          path: |
            target/manifest.json
            target/run_results.json
          retention-days: 30
          if-no-files-found: warn
